blueprint:
  name: Custody – Night Finalize + History (Dad/Mom/Other)
  description: >
    Finalizes at a set time. Restart-safe.
    Auto -> Final only when AUTO is Dad or Mom.
    Allows Other ONLY when manual override is ON and a typed reason is provided.
    Increments counters and writes a 14-night history string.
  domain: automation

  input:
    finalize_time:
      name: Finalize Time
      default: "04:05:00"
      selector:
        time: {}

    cutoff_time:
      name: Restart Cutoff Time
      default: "06:10:00"
      selector:
        time: {}

    auto_location:
      name: Auto Night Location (input_select)
      selector:
        entity:
          domain: input_select

    final_location:
      name: Final Night Location (input_select)
      selector:
        entity:
          domain: input_select

    night_locked:
      name: Night Locked Boolean
      selector:
        entity:
          domain: input_boolean

    night_counted:
      name: Night Counted Boolean
      selector:
        entity:
          domain: input_boolean

    manual_override:
      name: Manual Override Boolean
      selector:
        entity:
          domain: input_boolean

    other_reason:
      name: Other Location Text (required for Other)
      selector:
        entity:
          domain: input_text

    backfill_mode:
      name: Backfill Mode Boolean (optional)
      default: ""
      selector:
        entity:
          domain: input_boolean

    last_display_date:
      name: Display Date Text (night of)
      selector:
        entity:
          domain: input_text

    last_counted_location:
      name: Last Counted Location Text
      selector:
        entity:
          domain: input_text

    last_counted_date:
      name: Last Counted Date Text
      selector:
        entity:
          domain: input_text

    history_14:
      name: 14-Night History Text (input_text)
      selector:
        entity:
          domain: input_text

    counters_dad:
      name: Dad Counters (YTD + MTD)
      selector:
        entity:
          multiple: true
          domain: counter

    counters_mom:
      name: Mom Counters (YTD + MTD)
      selector:
        entity:
          multiple: true
          domain: counter

    counters_other:
      name: Other Counters (optional)
      default: []
      selector:
        entity:
          multiple: true
          domain: counter

    log_service:
      name: Optional logging service (ex: rest_command.custody_log)
      default: ""
      selector:
        text: {}

trigger:
  - platform: time
    at: !input finalize_time
  - platform: homeassistant
    event: start

condition:
  - condition: state
    entity_id: !input night_counted
    state: "off"

  - condition: time
    after: !input finalize_time
    before: !input cutoff_time

action:
  # Auto -> Final (only when Dad or Mom and not manual)
  - choose:
      - conditions:
          - condition: state
            entity_id: !input manual_override
            state: "off"
          - condition: template
            value_template: >
              {{ states(auto) in ['Dad','Mom'] }}
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input final_location
            data:
              option: "{{ states(auto) }}"
    variables:
      auto: !input auto_location

  # Gate: allow Dad/Mom; allow Other only with manual+typed reason
  - condition: template
    value_template: >
      {{
        states(final) in ['Dad','Mom']
        or (
          is_state(manual,'on')
          and states(final) == 'Other'
          and (states(reason)|trim|length > 0)
        )
      }}
    variables:
      final: !input final_location
      manual: !input manual_override
      reason: !input other_reason

  - service: input_boolean.turn_on
    target:
      entity_id:
        - !input night_locked
        - !input night_counted

  # Increment counters
  - choose:
      - conditions: "{{ states(final) == 'Dad' }}"
        sequence:
          - service: counter.increment
            target:
              entity_id: !input counters_dad

      - conditions: "{{ states(final) == 'Mom' }}"
        sequence:
          - service: counter.increment
            target:
              entity_id: !input counters_mom

      - conditions: "{{ states(final) == 'Other' }}"
        sequence:
          - service: counter.increment
            target:
              entity_id: !input counters_other

  # Metadata
  - service: input_text.set_value
    target:
      entity_id: !input last_counted_location
    data:
      value: "{{ states(final_ent) }}"
    variables:
      final_ent: !input final_location

  - service: input_text.set_value
    target:
      entity_id: !input last_counted_date
    data:
      value: "{{ now().date().isoformat() }}"

  # Display date = previous night unless backfill ON
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ backfill != '' and is_state(backfill,'on') }}"
        sequence: []
    default:
      - service: input_text.set_value
        target:
          entity_id: !input last_display_date
        data:
          value: "{{ (now() - timedelta(days=1)).date().isoformat() }}"
    variables:
      backfill: !input backfill_mode

  # 14-night history (pipe-delimited), rewrite-safe
  - variables:
      d: >-
        {% set dd = states(display_date_ent) %}
        {{ (dd|string|trim) if dd not in ['unknown','unavailable','', None]
           else (now() - timedelta(days=1)).date().isoformat() }}
      map:
        Dad: D
        Mom: M
        Other: O
      code: >-
        {% set f = states(final_ent) %}
        {{ map.get(f,'U') }}
      raw: "{{ states(history_ent) }}"
      parts: >-
        {% if raw in ['unknown','unavailable','', None] %}
          []
        {% else %}
          {{ raw.split('|') | map('trim') | list }}
        {% endif %}
      filtered: >-
        {% set out = [] %}
        {% for p in parts %}
          {% set p2 = p|trim %}
          {% if p2 and ':' in p2 %}
            {% set date_part = (p2.split(':')[0] | trim) %}
            {% set code_part = (p2.split(':')[1] | trim) %}
            {% if date_part != d and date_part|length == 10 %}
              {% set out = out + [date_part ~ ':' ~ code_part] %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ out }}
      new_value: "{{ ((filtered + [d ~ ':' ~ code])[-14:]) | join('|') }}"
    variables:
      display_date_ent: !input last_display_date
      final_ent: !input final_location
      history_ent: !input history_14

  - service: input_text.set_value
    target:
      entity_id: !input history_14
    data:
      value: "{{ new_value }}"

  # Optional logging hook
  - choose:
      - conditions: "{{ log != '' }}"
        sequence:
          - service: "{{ log }}"
    variables:
      log: !input log_service

mode: single
